apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feed-creator
  namespace: plaintext
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/server-snippet: |
      set $agentflag 0;

      if ($http_user_agent ~* "(Feedly)" ){
        set $agentflag 1;
      }

      if ($http_user_agent ~* "(Feedbin)" ){
        set $agentflag 1;
      }

      # if ($http_user_agent ~* "(Mozilla)" ){
      #   set $agentflag 1;
      # }

      # if ($http_user_agent ~* "(Firefox)" ){
      #   set $agentflag 1;
      # }

      if ($http_user_agent ~* "(Edg)" ){
        set $agentflag 1;
      }

      if ( $agentflag = 0 ) {
        return 403;
      }

    cert-manager.io/issuer: letsencrypt-prod

    # For Cloudflare proxied entries, set the TTL annotation to 1 (automatic), or do not set it.
    external-dns.alpha.kubernetes.io/ttl: "1"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - createfeed.andromedarabbit.net
      secretName: tls-feed-creator
  rules:
    - host: createfeed.andromedarabbit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feed-creator
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: feed-creator
  namespace: plaintext
  labels:
    app: feed-creator
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: feed-creator
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: feed-creator-data
#   namespace: plaintext
#   annotations: {}
#   labels:
#     app: feed-creator
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copy-feed-creator-scripts
  namespace: plaintext
data:
  copy.sh: |
    #!/bin/bash -xe
    export FEED_CREATOR_VERSION="2.2.3"

    aws s3 --endpoint=https://sgp1.digitaloceanspaces.com cp "s3://team7/store/feed-creator-${FEED_CREATOR_VERSION}.zip" /tmp/
    cd /tmp
    unzip "feed-creator-${FEED_CREATOR_VERSION}.zip"
    cp -Rf --preserve=all feed-creator-${FEED_CREATOR_VERSION}/* /var/www/html/

  run-nginx.sh: |
    #!/bin/bash -xe
    chmod -R g+rwX /var/www/html
    # chown -R 1001:1001 /var/www/html
    # chown 1001:1001 /opt/bitnami/nginx/html

    /entrypoint.sh /run.sh

  run-chown-php.sh: |
    #!/bin/bash -xe
    chmod -R g+rwX /var/www/html
    chown -R www-data:www-data /var/www/html

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-creator
  namespace: plaintext
  labels:
    app: feed-creator
spec:
  selector:
    matchLabels:
      app: feed-creator
  replicas: 1
  template:
    metadata:
      labels:
        app: feed-creator
    spec:
      imagePullSecrets:
        - name: github-andromedarabbit
      initContainers:
        - name: copy
          image: ghcr.io/unchartedsky/macgyver:fd216d4
          # command: ['sh', '-c', 'chmod -R g+rwX /opt/bitnami/wordpress']
          args:
            - /bin/bash
            - -c
            - "/scripts/copy.sh && /scripts/run-chown-php.sh"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup
                  key: aws_secret_access_key
          volumeMounts:
            - mountPath: /var/www/html
              name: feed-creator-data
            - name: scripts-d
              mountPath: /scripts
      containers:
        - name: app
          image: ghcr.io/unchartedsky/fulltextrss-base:00957490510ecc7abbcecca8a1ff94d36f9b1f42
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /var/www/html/custom_config.php
              name: feed-creator-secret
              subPath: custom_config.php
            - mountPath: /var/www/html
              name: feed-creator-data
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: feed-creator-secret
          secret:
            secretName: feed-creator
            items:
              - key: custom_config.php
                path: custom_config.php
        # - name: feed-creator-config
        #   configMap:
        #     name: feed-creator-configmap
        # - name: feed-creator-data
        #   persistentVolumeClaim:
        #     claimName: feed-creator-data
        - name: feed-creator-data
          emptyDir: {}
        - name: scripts-d
          projected:
            defaultMode: 500
            sources:
              - configMap:
                  name: copy-feed-creator-scripts
                  items:
                    - key: copy.sh
                      path: copy.sh
                    - key: run-chown-php.sh
                      path: run-chown-php.sh
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nginx-data
#   namespace: plaintext
#   annotations: {}
#   labels:
#     app: nginx
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
