apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fulltextrss
  namespace: plaintext
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/server-snippet: |
      set $agentflag 0;

      if ($http_user_agent ~* "(Feedly)" ){
        set $agentflag 1;
      }

      if ($http_user_agent ~* "(Feedbin)" ){
        set $agentflag 1;
      }

      # if ($http_user_agent ~* "(Mozilla)" ){
      #   set $agentflag 1;
      # }

      # if ($http_user_agent ~* "(Firefox)" ){
      #   set $agentflag 1;
      # }

      if ($http_user_agent ~* "(Edg)" ){
        set $agentflag 1;
      }

      if ( $agentflag = 0 ) {
        return 403;
      }

    cert-manager.io/issuer: letsencrypt-prod

    # For Cloudflare proxied entries, set the TTL annotation to 1 (automatic), or do not set it.
    external-dns.alpha.kubernetes.io/ttl: "1"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  tls:
  - hosts:
    - feed.andromedarabbit.net
    secretName: tls-fulltextrss
  rules:
  - host: feed.andromedarabbit.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fulltextrss
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fulltextrss
  namespace: plaintext
  labels:
    app: fulltextrss
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: fulltextrss
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: fulltextrss-data
#   namespace: plaintext
#   annotations: {}
#   labels:
#     app: fulltextrss
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: copy-fulltextrss-scripts
  namespace: plaintext
data:
  copy.sh: |
    #!/bin/bash -xe
    export FULLTEXTRSS_VERSION="3.9.11"

    aws s3 --endpoint=https://sgp1.digitaloceanspaces.com cp "s3://team7/store/full-text-rss-${FULLTEXTRSS_VERSION}.zip" /tmp/
    cd /tmp
    unzip "full-text-rss-${FULLTEXTRSS_VERSION}.zip"
    cp -Rf --preserve=all full-text-rss-${FULLTEXTRSS_VERSION}/* /var/www/html/

  run-nginx.sh: |
    #!/bin/bash -xe
    chmod -R g+rwX /var/www/html
    # chown -R 1001:1001 /var/www/html
    # chown 1001:1001 /opt/bitnami/nginx/html

    /entrypoint.sh /run.sh

  run-chown-php.sh: |
    #!/bin/bash -xe
    chmod -R g+rwX /var/www/html
    chown -R www-data:www-data /var/www/html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fulltextrss-site-config
  namespace: plaintext
data:
  m.blog.naver.com.txt: |
    title: //meta[@property='og:title']
    body: //div[@class='se-main-container']
    # strip_image_src: og_default_image
    replace_string(https://blog.naver.com): https://m.blog.naver.com
    # replace_string(<meta property="og:image" content="https://blogimgs.pstatic.net/nblog/mylog/post/og_default_image_160610.png"/>):
    # strip_id_or_class: hidden
    tidy: yes
    prune: no
    test_url: https://m.blog.naver.com/ldk27/222286793132

  # m.post.naver.com.txt: |
  #   title: //meta[@property='og:title']
  #   body: //div[@class='se_component_wrap']
  #   # strip_image_src: og_default_image
  #   replace_string(https://post.naver.com): https://m.post.naver.com
  #   # replace_string(<meta property="og:image" content="https://blogimgs.pstatic.net/nblog/mylog/post/og_default_image_160610.png"/>):
  #   # strip_id_or_class: hidden
  #   tidy: yes
  #   prune: no
  #   test_url: https://m.post.naver.com/viewer/postView.naver?volumeNo=32821394&memberNo=18265860

  # project-syndicate.org.txt: |
  #   # body: //div[@class='article__container']
  #   # strip: //nav
  #   # strip_id_or_class: article__sidebar
  #   # strip_id_or_class: article__footer-widget
  #   strip_id_or_class: search__box
  #   strip_id_or_class: remodal
  #   strip_id_or_class: form
  #   strip_id_or_class: track-event
  #   tidy: yes
  #   prune: yes
  #   test_url: https://www.project-syndicate.org/commentary/post-covid-instability-sources-of-unrest-by-kent-harrington-2021-03
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulltextrss
  namespace: plaintext
  labels:
    app: fulltextrss
spec:
  selector:
    matchLabels:
      app: fulltextrss
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fulltextrss
    spec:
      imagePullSecrets:
      - name: github-andromedarabbit
      securityContext:
        fsGroup: 33
      initContainers:
      - name: copy
        image: ghcr.io/unchartedsky/macgyver:fd216d4
        # command: ['sh', '-c', 'chmod -R g+rwX /opt/bitnami/wordpress']
        args:
        - /bin/bash
        - -c
        - "/scripts/copy.sh && /scripts/run-chown-php.sh"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backup
              key: aws_access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backup
              key: aws_secret_access_key
        volumeMounts:
        - mountPath: /var/www/html
          name: fulltextrss-data
        - name: scripts-d
          mountPath: /scripts
      containers:
      - name: app
        image: ghcr.io/unchartedsky/fulltextrss-base:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /var/www/html/custom_config.php
          name: fulltextrss-secret
          subPath: custom_config.php
        - mountPath: /var/www/html/site_config/custom
          name: fulltextrss-site-config
        - mountPath: /var/www/html
          name: fulltextrss-data
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
      restartPolicy: Always
      volumes:
      - name: fulltextrss-secret
        secret:
          secretName: fulltextrss
          items:
          - key: custom_config.php
            path: custom_config.php
      - name: fulltextrss-site-config
        configMap:
          name: fulltextrss-site-config
      # - name: fulltextrss-data
      #   persistentVolumeClaim:
      #     claimName: fulltextrss-data
      - name: fulltextrss-data
        emptyDir: {}
      - name: scripts-d
        projected:
          defaultMode: 500
          sources:
          - configMap:
              name: copy-fulltextrss-scripts
              items:
              - key: copy.sh
                path: copy.sh
              - key: run-chown-php.sh
                path: run-chown-php.sh
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nginx-data
#   namespace: plaintext
#   annotations: {}
#   labels:
#     app: nginx
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
