apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-limit
  namespace: ingress-nginx
spec:
  hard:
    pods: "30"
